FROM node:16

# Clonar el repositorio del frontend desde Git
RUN git clone https://github.com/tu_usuario/frontend.git /app

# Configurar el directorio de trabajo
WORKDIR /app

# Instalar dependencias y construir la aplicación Angular
RUN npm install
RUN npm run build -- --prod
