FROM php:8.1-fpm

# Instalar las dependencias necesarias
RUN apt-get update && apt-get install -y \
    curl \
    git \
    libpq-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-install pdo pdo_sqlsrv

# Instalar controladores de SQL Server para PHP
RUN curl -o /etc/apt/trusted.gpg.d/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc && \
    curl -o /etc/apt/sources.list.d/mssql-release.list https://packages.microsoft.com/config/debian/10/prod.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev && \
    pecl install sqlsrv pdo_sqlsrv && \
    docker-php-ext-enable sqlsrv pdo_sqlsrv

# Clonar el repositorio del backend desde Git
RUN git clone https://github.com/tu_usuario/backend.git /var/www

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Instalar las dependencias de Laravel
RUN composer install

CMD ["php-fpm"]
